# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "shell", privileged: false, path: "ruby.sh"
  config.vm.provision "shell", privileged: true, path: "../vagrant.sh"
end
