# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.provision "shell", privileged: false, path: "../ruby/ruby"
  config.vm.provision "shell", privileged: false, path: "rails"
  config.vm.provision "shell", privileged: true, path: "../vagrant.sh"
  config.vm.network "forwarded_port", guest: 3000, host: 3000
  config.vm.synced_folder "./", "/vagrant"
end
